previewsEnabled: true

services:
  - type: web
    name: ai-assistant
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput
    startCommand: daphne -b 0.0.0.0 -p 8000 ai_assistant.asgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "calendar-application-iiz6.onrender.com"
      - key: DISABLE_COLLECTSTATIC
        value: "1"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false

databases:
  - name: ai-assistant-db
    plan: free
    region: oregon
