# Generated by Django 5.2.6 on 2026-03-19 11:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expiry', models.DateTimeField()),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('thread_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('snippet', models.TextField(blank=True, max_length=500)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('folder', models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('draft', 'Draft'), ('trash', 'Trash'), ('spam', 'Spam')], default='inbox', max_length=20)),
                ('category', models.CharField(choices=[('important', 'Important'), ('personal', 'Personal'), ('promotions', 'Promotions'), ('social', 'Social'), ('updates', 'Updates'), ('forums', 'Forums')], default='personal', max_length=20)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_suggested_reply', models.TextField(blank=True)),
                ('ai_intent_detected', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emails',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['user', 'received_at'], name='emails_user_id_f34052_idx'), models.Index(fields=['gmail_message_id'], name='emails_gmail_m_c3898a_idx'), models.Index(fields=['thread_id'], name='emails_thread__8b949f_idx')],
            },
        ),
    ]
